import {
    createSectionFactory as e,
    createBaseSections as a,
} from '../index.mjs';
const n = /* #__PURE__ */ e('ut'),
    {
        outer: l,
        inner: t,
        wrapper: d,
        label: r,
        prefix: i,
        suffix: o,
        help: u,
        messages: s,
        message: $,
        icon: p,
    } = /* #__PURE__ */ a(n),
    c = n('input', () => ({
        $el: 'input',
        bind: '$attrs',
        attrs: {
            name: '$node.name',
            autocomplete: '$attrs.autocomplete || off',
            id: '$id',
            onChange: '$handlers.handleInput',
            onBlur: '$handlers.unitBlur',
            onInput: '$handlers.handleInput',
            onKeydown: '$handlers.handleKeyDown',
            onBeforeinput: '$handlers.handleBeforeInput',
            readonly: '$readonly',
            inputmode: 'decimal',
            placeholder: '$placeholder || $unitParts.unit',
            disabled: '$disabled',
            'data-unit': '$unit',
            'data-currency': '$currency',
            'data-display-locale': '$displayLocale',
            'data-value-locale': '$valueLocale',
            'data-decimals': '$decimals',
            'data-trailing': '$trailingZeros',
            'data-numeric-value': '$_numericValue',
            'data-align': '$_valueAlignAuto',
            'aria-required': '$state.required || undefined',
        },
    }));
export {
    n as createSection,
    u as help,
    p as icon,
    t as inner,
    c as input,
    r as label,
    $ as message,
    s as messages,
    l as outer,
    i as prefix,
    o as suffix,
    d as wrapper,
};
